import type { Tema } from '../motor/tipos.ts';

const tema = (id: string, titulo: string, nombres: string[]): Tema => ({
  id,
  titulo,
  propio: false,
  items: nombres.map((nombre, i) => ({ id: `${id}-${i + 1}`, nombre })),
});

export const TEMAS: Tema[] = [
  tema('futbol', 'Leyendas del fútbol', [
    'Pelé', 'Maradona', 'Johan Cruyff', 'Di Stéfano', 'Beckenbauer', 'Zidane',
    'Ronaldo Nazário', 'Messi', 'Cristiano Ronaldo', 'Ronaldinho', 'Iniesta',
    'Xavi', 'Buffon', 'Paolo Maldini', 'Roberto Carlos', 'Puyol', 'Casillas',
    'Raúl', 'Thierry Henry', 'Totti', 'Zlatan', 'Kaká', 'Modrić', 'Mbappé',
    'Garrincha', 'Eusébio', 'Platini', 'Baggio', 'Van Basten', 'Gullit',
    'Rijkaard', 'Romário', 'Rivaldo', 'Bebeto', 'Cafú', 'Dida', 'Sócrates',
    'Zico', 'Falcao', 'Butragueño', 'Míchel', 'Hierro', 'Guardiola', 'Luis Enrique',
    'Fernando Torres', 'David Villa', 'Xabi Alonso', 'Sergio Ramos', 'Busquets',
    'Piqué', 'Silva', 'Cesc', 'Rooney', 'Beckham', 'Gerrard', 'Lampard',
    'Scholes', 'Giggs', 'Cantona', 'Van Nistelrooy', 'Bergkamp', 'Vieira',
    'Drogba', 'Eto\'o', 'Kanté', 'Pirlo', 'Nesta', 'Cannavaro', 'Del Piero',
    'Inzaghi', 'Shevchenko', 'Ibrahimović', 'Lewandowski', 'Neuer', 'Müller',
    'Klose', 'Ballack', 'Kahn', 'Matthäus', 'Rummenigge', 'Figo', 'Rui Costa',
    'Deco', 'Suárez', 'Neymar', 'Haaland', 'Salah', 'De Bruyne', 'Kroos',
    'Benzema', 'Bale', 'Marcelo', 'Alves', 'Ferdinand', 'Terry', 'Carles Rexach',
    'Maldonado', 'Hagi', 'Stoichkov', 'Weah', 'Okocha', 'Kluivert',
  ]),
  tema('ciudades', 'Ciudades del mundo', [
    'Tokio', 'Nueva York', 'París', 'Roma', 'Barcelona', 'Londres', 'Madrid',
    'Estambul', 'Río de Janeiro', 'Ciudad del Cabo', 'Sídney', 'Kioto',
    'Marrakech', 'Lisboa', 'Praga', 'Buenos Aires', 'Bangkok', 'Seúl',
    'Ámsterdam', 'San Francisco', 'El Cairo', 'Venecia', 'Singapur', 'Berlín',
    'Viena', 'Budapest', 'Copenhague', 'Estocolmo', 'Oslo', 'Helsinki',
    'Reikiavik', 'Dublín', 'Edimburgo', 'Bruselas', 'Múnich', 'Hamburgo',
    'Zúrich', 'Ginebra', 'Milán', 'Florencia', 'Nápoles', 'Atenas',
    'Santorini', 'Dubrovnik', 'Liubliana', 'Varsovia', 'Cracovia', 'Moscú',
    'San Petersburgo', 'Oporto', 'Sevilla', 'Valencia', 'Bilbao', 'Granada',
    'San Sebastián', 'Palma', 'Las Palmas', 'Toronto', 'Vancouver', 'Montreal',
    'Chicago', 'Los Ángeles', 'Miami', 'Nueva Orleans', 'Boston', 'Seattle',
    'Austin', 'Ciudad de México', 'Oaxaca', 'La Habana', 'Cartagena',
    'Medellín', 'Bogotá', 'Lima', 'Cusco', 'Santiago de Chile', 'Montevideo',
    'São Paulo', 'Salvador de Bahía', 'Dubái', 'Doha', 'Tel Aviv', 'Petra',
    'Bombay', 'Nueva Delhi', 'Jaipur', 'Katmandú', 'Shanghái', 'Pekín',
    'Hong Kong', 'Taipéi', 'Osaka', 'Hanói', 'Ho Chi Minh', 'Kuala Lumpur',
    'Bali', 'Manila', 'Melbourne', 'Auckland', 'Nairobi', 'Zanzíbar',
  ]),
  tema('paises', 'Países para vivir', [
    'España', 'Italia', 'Japón', 'Portugal', 'Noruega', 'Suiza', 'Canadá',
    'Australia', 'Nueva Zelanda', 'México', 'Argentina', 'Brasil', 'Grecia',
    'Tailandia', 'Corea del Sur', 'Países Bajos', 'Islandia', 'Costa Rica',
    'Marruecos', 'Estados Unidos', 'Irlanda', 'Croacia', 'Francia', 'Alemania',
    'Reino Unido', 'Bélgica', 'Austria', 'Dinamarca', 'Suecia', 'Finlandia',
    'Polonia', 'Chequia', 'Hungría', 'Eslovenia', 'Estonia', 'Malta', 'Chipre',
    'Turquía', 'Israel', 'Emiratos Árabes', 'Catar', 'Egipto', 'Túnez',
    'Sudáfrica', 'Kenia', 'Namibia', 'Senegal', 'Etiopía', 'India', 'Nepal',
    'Vietnam', 'Indonesia', 'Malasia', 'Singapur', 'Filipinas', 'China',
    'Taiwán', 'Chile', 'Uruguay', 'Perú', 'Colombia', 'Ecuador', 'Panamá',
    'Cuba', 'República Dominicana', 'Jamaica', 'Bolivia', 'Paraguay',
    'Guatemala', 'Islas Feroe', 'Groenlandia', 'Luxemburgo', 'Mónaco',
    'Andorra', 'Escocia', 'Gales', 'Rumanía', 'Bulgaria', 'Serbia',
    'Montenegro', 'Albania', 'Georgia', 'Armenia', 'Kazajistán', 'Mongolia',
    'Sri Lanka', 'Maldivas', 'Seychelles', 'Mauricio', 'Fiyi', 'Samoa',
  ]),
  tema('planes', 'Planes de fin de semana', [
    'Escapada a la playa', 'Cena de amigos', 'Maratón de series', 'Concierto',
    'Ruta de senderismo', 'Festival de música', 'Partido en el estadio',
    'Spa y desconexión', 'Escape room', 'Mercadillo', 'Barbacoa',
    'Noche de bar', 'Museo', 'Karaoke', 'Roadtrip', 'Acampada',
    'Cine en casa', 'Brunch', 'Noche de videojuegos', 'Piscina',
    'Ruta de tapas', 'Feria del pueblo', 'Partida de cartas', 'Bolera',
    'Paintball', 'Karts', 'Ruta en bici', 'Kayak', 'Surf', 'Esquí',
    'Vía ferrata', 'Escalada', 'Padel con los amigos', 'Fútbol sala',
    'Baño en un río', 'Ver el amanecer', 'Noche de estrellas', 'Cata de vinos',
    'Bodega', 'Mercado gastronómico', 'Food truck', 'Cena en casa cocinando',
    'Puzzle de 2000 piezas', 'Juegos de mesa', 'Trivial', 'Rol en mesa',
    'Maratón de Marvel', 'Documentales', 'Teatro', 'Monólogos', 'Musical',
    'Ópera', 'Exposición de fotografía', 'Feria del libro', 'Biblioteca',
    'Tatuaje nuevo', 'Corte de pelo radical', 'Compras', 'Ikea', 'Outlet',
    'Ordenar la casa', 'No hacer absolutamente nada', 'Dormir doce horas',
    'Llamar a la familia', 'Comida en casa de la abuela', 'Visitar a un amigo',
    'Ir al pueblo', 'Excursión al monte', 'Playa nudista', 'Aguas termales',
    'Parque de atracciones', 'Zoo', 'Acuario', 'Planetario', 'Castillo',
    'Pueblo medieval', 'Casa rural', 'Glamping', 'Furgoneta camper',
    'Tren nocturno', 'Vuelo de última hora', 'Crucero de un día',
    'Clase de cocina', 'Clase de baile', 'Yoga', 'Correr una carrera',
    'Voluntariado', 'Recogida de basura en la playa',
  ]),
  tema('comida', 'Comida favorita', [
    'Pizza', 'Sushi', 'Paella', 'Hamburguesa', 'Tacos', 'Ramen', 'Jamón',
    'Tortilla de patatas', 'Croquetas', 'Pasta carbonara', 'Pollo asado',
    'Bocadillo de calamares', 'Cocido', 'Curry', 'Kebab', 'Empanada',
    'Churros', 'Tarta de queso', 'Helado', 'Ensaladilla rusa', 'Lasaña',
    'Canelones', 'Risotto', 'Pizza cuatro quesos', 'Pad thai', 'Dim sum',
    'Gyozas', 'Tempura', 'Poke', 'Ceviche', 'Arepas', 'Burrito', 'Nachos',
    'Guacamole', 'Fajitas', 'Chili con carne', 'Costillas a la barbacoa',
    'Entrecot', 'Chuletón', 'Solomillo', 'Cordero asado', 'Cochinillo',
    'Pulpo a la gallega', 'Gambas al ajillo', 'Boquerones', 'Anchoas',
    'Salmón ahumado', 'Bacalao al pil pil', 'Merluza rebozada', 'Marmitako',
    'Fabada', 'Lentejas', 'Garbanzos con espinacas', 'Gazpacho', 'Salmorejo',
    'Pisto', 'Escalivada', 'Pan con tomate', 'Tortilla de camarones',
    'Patatas bravas', 'Pimientos de padrón', 'Torreznos', 'Morcilla',
    'Chorizo', 'Queso manchego', 'Tabla de quesos', 'Fondue', 'Raclette',
    'Sopa de cebolla', 'Quiche', 'Crepes', 'Gofres', 'Tortitas', 'Tostada con aguacate', 'Huevos rotos', 'Huevos benedictinos', 'Bikini', 'Sándwich club',
    'Perrito caliente', 'Alitas de pollo', 'Pollo frito', 'Fish and chips',
    'Falafel', 'Hummus', 'Shawarma', 'Cuscús', 'Tajine', 'Biryani',
    'Bibimbap', 'Bao', 'Pho', 'Rollitos de primavera', 'Arroz tres delicias',
    'Flan', 'Natillas', 'Arroz con leche', 'Torrijas', 'Tiramisú', 'Brownie',
    'Cookies', 'Donuts', 'Croissant', 'Ensaimada', 'Roscón de reyes',
  ]),
  tema('peliculas', 'Películas imprescindibles', [
    'El Padrino', 'El Padrino II', 'Pulp Fiction', 'Origen', 'Interstellar',
    'Matrix', 'El Señor de los Anillos', 'Cadena perpetua', 'Parásitos',
    'Gladiator', 'Regreso al futuro', 'Titanic', 'Forrest Gump',
    'El club de la lucha', 'Los Otros', 'REC', 'Tiburón', 'Alien', 'Toy Story',
    'Coco', 'Whiplash', 'Uno de los nuestros', 'Casino', 'Taxi Driver',
    'Apocalypse Now', 'Full Metal Jacket', 'La chaqueta metálica',
    'El resplandor', '2001: Una odisea del espacio', 'La naranja mecánica',
    'Psicosis', 'Vértigo', 'La ventana indiscreta', 'Casablanca',
    'Ciudadano Kane', 'El golpe', 'Doce hombres sin piedad', 'Éxodo',
    'El silencio de los corderos', 'Seven', 'Zodiac', 'La red social',
    'El caballero oscuro', 'Batman Begins', 'Joker', 'Los Vengadores',
    'Infinity War', 'Spider-Man: Un nuevo universo', 'Star Wars: Episodio V',
    'Star Wars: Una nueva esperanza', 'Indiana Jones', 'Jurassic Park',
    'E.T.', 'La lista de Schindler', 'Salvar al soldado Ryan', 'Munich',
    'Malditos bastardos', 'Django desencadenado', 'Kill Bill', 'Reservoir Dogs',
    'Sin perdón', 'El bueno, el feo y el malo', 'Érase una vez en América',
    'Blade Runner', 'Blade Runner 2049', 'Mad Max: Furia en la carretera',
    'Dune', 'Arrival', 'Gravity', 'Marte', 'Contact', 'Doce monos',
    'El show de Truman', 'Olvídate de mí', 'Her', 'Lost in Translation',
    'Amelie', 'La vida es bella', 'Cinema Paradiso', 'Roma', 'Amores perros',
    'El laberinto del fauno', 'Volver', 'Todo sobre mi madre', 'Mar adentro',
    'Los lunes al sol', 'El día de la bestia', 'Airbag', 'Torrente',
    'Ocho apellidos vascos', 'Celda 211', 'La isla mínima', 'Un monstruo viene a verme',
    'Up', 'Wall-E', 'Ratatouille', 'Del revés', 'Buscando a Nemo',
    'El rey león', 'Aladdín', 'La bella y la bestia', 'El viaje de Chihiro',
    'La princesa Mononoke', 'Akira', 'Your Name',
  ]),
  tema('series', 'Series para maratón', [
    'Breaking Bad', 'Los Soprano', 'The Wire', 'Juego de Tronos', 'Friends',
    'The Office', 'Chernobyl', 'Dark', 'Better Call Saul', 'Peaky Blinders',
    'Stranger Things', 'La casa de papel', 'Succession', 'True Detective',
    'Fargo', 'Black Mirror', 'Los Simpson', 'Narcos', 'Sherlock', 'Perdidos',
    'Mad Men', 'House of Cards', 'Homeland', '24', 'Prison Break', 'Dexter',
    'House', 'Urgencias', 'Anatomía de Grey', 'Doctor en Alaska',
    'Cómo conocí a vuestra madre', 'Big Bang Theory', 'Seinfeld', 'Frasier',
    'Padre de familia', 'South Park', 'Rick y Morty', 'Bojack Horseman',
    'Arrested Development', 'Parks and Recreation', 'Brooklyn Nine-Nine',
    'Community', 'Ted Lasso', 'Fleabag', 'Killing Eve', 'The Crown',
    'Downton Abbey', 'Vikingos', 'The Last Kingdom', 'Roma', 'Espartaco',
    'The Walking Dead', 'The Last of Us', 'The Boys', 'Watchmen', 'Legión',
    'Daredevil', 'The Mandalorian', 'Andor', 'Firefly', 'Battlestar Galactica',
    'Expediente X', 'Fringe', 'Westworld', 'Devs', 'Severance', 'Mr. Robot',
    'Sense8', 'Sex Education', 'Élite', 'Merlí', 'Física o Química',
    'Aquí no hay quien viva', 'La que se avecina', 'Los Serrano', 'Cuéntame',
    'Águila Roja', 'El Ministerio del Tiempo', 'Vis a vis', 'Antidisturbios',
    'Patria', 'Hierro', 'El embarcadero', 'Veneno', 'Paquita Salas',
    'Squid Game', 'Alice in Borderland', 'Kingdom', 'Shogun', 'Tokyo Vice',
    'Ozark', 'Bloodline', 'Godless', 'Yellowstone', 'Justified', 'Banshee',
    'Sons of Anarchy', 'The Shield', 'Boardwalk Empire', 'Deadwood',
  ]),
  tema('musica', 'Artistas musicales', [
    'The Beatles', 'Queen', 'Michael Jackson', 'Pink Floyd', 'Nirvana',
    'Bob Marley', 'Beyoncé', 'Rosalía', 'Bad Bunny', 'Daft Punk', 'Adele',
    'Kendrick Lamar', 'Extremoduro', 'Estopa', 'AC/DC', 'Metallica',
    'Radiohead', 'Amy Winehouse', 'Coldplay', 'Rihanna', 'The Rolling Stones',
    'Led Zeppelin', 'The Who', 'David Bowie', 'Prince', 'Elvis Presley',
    'Johnny Cash', 'Bob Dylan', 'Bruce Springsteen', 'U2', 'R.E.M.',
    'Oasis', 'Blur', 'The Smiths', 'Joy Division', 'The Cure', 'Depeche Mode',
    'New Order', 'Talking Heads', 'The Clash', 'Sex Pistols', 'Ramones',
    'Guns N\' Roses', 'Aerosmith', 'Deep Purple', 'Black Sabbath', 'Iron Maiden',
    'Pearl Jam', 'Soundgarden', 'Red Hot Chili Peppers', 'Rage Against the Machine',
    'System of a Down', 'Linkin Park', 'Green Day', 'The Killers',
    'Arctic Monkeys', 'Tame Impala', 'Gorillaz', 'Massive Attack', 'Portishead',
    'Björk', 'Aphex Twin', 'The Chemical Brothers', 'The Prodigy', 'Fatboy Slim',
    'Avicii', 'Calvin Harris', 'Skrillex', 'Stevie Wonder', 'Marvin Gaye',
    'Aretha Franklin', 'Nina Simone', 'Ella Fitzgerald', 'Frank Sinatra',
    'Ray Charles', 'James Brown', 'Tina Turner', 'Whitney Houston',
    'Mariah Carey', 'Madonna', 'Lady Gaga', 'Taylor Swift', 'Billie Eilish',
    'Dua Lipa', 'The Weeknd', 'Drake', 'Eminem', 'Tupac', 'Notorious B.I.G.',
    'Jay-Z', 'Nas', 'Wu-Tang Clan', 'Snoop Dogg', 'Dr. Dre', 'Travis Scott',
    'Héroes del Silencio', 'Los Planetas', 'Vetusta Morla', 'Love of Lesbian',
    'Fito y Fitipaldis', 'Mecano', 'Joaquín Sabina', 'Serrat', 'Camarón',
    'Paco de Lucía', 'Enrique Morente', 'C. Tangana', 'Quevedo', 'Aitana',
    'Shakira', 'Juanes', 'Maná', 'Soda Stereo', 'Gustavo Cerati', 'Charly García',
  ]),
  tema('superpoderes', 'Superpoderes', [
    'Volar', 'Invisibilidad', 'Teletransporte', 'Leer la mente',
    'Parar el tiempo', 'Viajar en el tiempo', 'Superfuerza', 'Inmortalidad',
    'Curación instantánea', 'Respirar bajo el agua', 'Hablar todos los idiomas',
    'Controlar el clima', 'Duplicarte', 'No necesitar dormir', 'Suerte infinita',
    'Cambiar de forma', 'Telequinesis', 'Ver el futuro', 'Supervelocidad',
    'Atravesar paredes', 'Hacerte gigante', 'Hacerte diminuto',
    'Controlar el fuego', 'Controlar el agua', 'Controlar el hielo',
    'Controlar la electricidad', 'Controlar las plantas', 'Controlar el metal',
    'Controlar la gravedad', 'Controlar la luz', 'Controlar las sombras',
    'Hablar con los animales', 'Hablar con los muertos', 'Memoria perfecta',
    'Aprender cualquier cosa en un minuto', 'Cálculo instantáneo',
    'Persuasión absoluta', 'Detectar mentiras', 'Copiar habilidades ajenas',
    'Regenerar miembros', 'Piel indestructible', 'Visión de rayos X',
    'Visión nocturna', 'Superoído', 'Olfato de sabueso', 'Puntería perfecta',
    'Equilibrio perfecto', 'Trepar paredes', 'Nadar como un pez',
    'No sentir dolor', 'No sentir frío ni calor', 'No necesitar comer',
    'No envejecer', 'Comer sin engordar', 'Resaca imposible',
    'Aparcar siempre en la puerta', 'Que nunca te pillen los atascos',
    'Wifi mental', 'Cargar el móvil con la mano', 'Silenciar a alguien',
    'Rebobinar cinco minutos', 'Guardar partida y recargar', 'Pausar el mundo',
    'Soñar lo que quieras', 'Despertar descansado siempre',
    'Cambiar de cara', 'Imitar cualquier voz', 'Volverte intangible',
    'Crear portales', 'Invocar objetos', 'Reparar cualquier cosa al tocarla',
    'Multiplicar el dinero', 'Traducir animales', 'Respirar en el espacio',
    'Sobrevivir a cualquier caída', 'Escudo de energía', 'Rayo de las manos',
    'Convertir cosas en oro', 'Hacer llover', 'Encontrar cualquier objeto perdido',
  ]),
  tema('videojuegos', 'Videojuegos legendarios', [
    'Tetris', 'Super Mario Bros', 'The Legend of Zelda', 'Minecraft', 'GTA V',
    'Half-Life 2', 'Dark Souls', 'The Last of Us', 'Elden Ring',
    'Red Dead Redemption 2', 'Fortnite', 'Counter-Strike', 'FIFA',
    'Pokémon Rojo', 'Portal', 'Doom', 'Age of Empires II', 'Among Us',
    'Super Mario 64', 'Mario Kart', 'Super Smash Bros', 'Zelda: Ocarina of Time',
    'Zelda: Breath of the Wild', 'Metroid Prime', 'Castlevania', 'Mega Man',
    'Sonic the Hedgehog', 'Street Fighter II', 'Mortal Kombat', 'Tekken',
    'Pac-Man', 'Space Invaders', 'Donkey Kong', 'Final Fantasy VII',
    'Chrono Trigger', 'Secret of Mana', 'Dragon Quest', 'Persona 5',
    'The Witcher 3', 'Skyrim', 'Oblivion', 'Fallout 3', 'Fallout: New Vegas',
    'Mass Effect 2', 'Dragon Age: Origins', 'Baldur\'s Gate 3', 'Diablo II',
    'World of Warcraft', 'StarCraft', 'Warcraft III', 'Command & Conquer',
    'Civilization VI', 'SimCity', 'Los Sims', 'RollerCoaster Tycoon',
    'Football Manager', 'Pro Evolution Soccer', 'NBA 2K', 'Gran Turismo',
    'Forza Horizon', 'Need for Speed', 'Mario Kart 8', 'Rocket League',
    'Halo: Combat Evolved', 'Call of Duty 4', 'Battlefield 3', 'Overwatch',
    'Team Fortress 2', 'Valorant', 'League of Legends', 'Dota 2', 'Apex Legends',
    'PUBG', 'Rainbow Six Siege', 'Escape from Tarkov', 'Rust', 'Terraria',
    'Stardew Valley', 'Animal Crossing', 'Hollow Knight', 'Celeste', 'Hades',
    'Cuphead', 'Undertale', 'Bloodborne', 'Sekiro', 'Nioh', 'Monster Hunter',
    'Resident Evil 4', 'Silent Hill 2', 'Dead Space', 'Outlast', 'Amnesia',
    'BioShock', 'Deus Ex', 'Dishonored', 'Hitman', 'Metal Gear Solid',
    'Splinter Cell', 'Assassin\'s Creed II', 'Uncharted 2', 'Tomb Raider',
    'God of War', 'Shadow of the Colossus', 'Journey', 'Limbo', 'Braid',
    'Kerbal Space Program', 'Factorio', 'Rimworld', 'Slay the Spire',
  ]),
];

export const temaPorId = (id: string): Tema | undefined =>
  TEMAS.find((t) => t.id === id);
